$wallpaper = ~/.config/hypr/wallpaper/hello-word.png
exec-once = $terminal

exec-once = awww-daemon

exec-once = sleep 1 && awww img $wallpaper

exec-once = waybar

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
