################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = hyprlauncher

$path = ~/.config/hypr

#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

source = $path/core/exec.conf


#############################
### ENVIRONMENT VARIABLES ###
#############################


source = $path/core/env.conf


#####################
### LOOK AND FEEL ###
#####################

source = $path/ui/general.conf
source = $path/ui/decoration.conf
source = $path/ui/animations.conf

# https://wiki.hypr.land/Configuring/Variables/#animations
# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
source = $path/core/hardware.conf


###################
### KEYBINDINGS ###
###################

source = $path/core/keybinds.conf 

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
source = $path/ui/windows.conf
